### ISSUE TITLE
Installation on Windows - RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by BrknKybrd** [facebookresearch/pytorch3d#323]
## ❓ Questions on how to use PyTorch3D

Good day,

i am trying to install pytorch3D on a windows machine following the instructions in install.md starting from a fresh conda environment. However, the process is failing with the error message (ran in x86_x6 Cross Tools Command Prompt for VS 2019):

`File "E:\conda-env\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension`

I would appreciate any help you can give

# full error message
[full.txt](https://github.com/facebookresearch/pytorch3d/files/5089302/full.txt)

# conda info
```
(E:\conda-env) C:\Users\voglf\Downloads\pytorch3d-master>conda info

     active environment : E:\conda-env
    active env location : E:\conda-env
            shell level : 1
       user config file : C:\Users\voglf\.condarc
 populated config files :
          conda version : 4.8.4
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\voglf\.conda\pkgs
                          C:\Users\voglf\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\voglf\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\voglf\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

# conda list
```
(E:\conda-env) C:\Users\voglf\Downloads\pytorch3d-master>conda list
# packages in environment at E:\conda-env:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py38_0
cudatoolkit               10.2.89              h74a9793_1
freetype                  2.10.2               hd328e21_0
fvcore                    0.1.1.post20200716            py_0    conda-forge
intel-openmp              2020.1                      216
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.1.0                h56a325e_1
lz4-c                     1.9.2                h62dcd97_1
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.1.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
ninja                     1.10.0           py38h7ef1ec2_0
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
olefile                   0.46                       py_0
openssl                   1.1.1g               he774522_1
pillow                    7.2.0            py38hcc1f983_0
pip                       20.2.2                   py38_0
portalocker               1.7.0            py38h32f6830_0    conda-forge
python                    3.8.5                he1778fa_0
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.5.1           py3.8_cuda102_cudnn7_0    pytorch
pywin32                   227              py38hfa6e2cd_0    conda-forge
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
setuptools                49.6.0                   py38_0
six                       1.15.0                     py_0
sqlite                    3.32.3               h2a8f88b_0
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               he774522_0
torchvision               0.6.1                py38_cu102    pytorch
tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.34.2                   py38_0
wincertstore              0.2                      py38_0
xz                        5.2.5                h62dcd97_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0
```

**Comment by bottler** [comment]
The full error message shows that you've got these errors, which have been reported elsewhere.
```
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(474): error: member "torch::jit::detail::ModulePolicy::all_slots" may not be initialized
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(487): error: member "torch::jit::detail::ParameterPolicy::all_slots" may not be initialized
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(501): error: member "torch::jit::detail::BufferPolicy::all_slots" may not be initialized
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(514): error: member "torch::jit::detail::AttributePolicy::all_slots" may not be initialized
```

It looks like this might work in pytorch 1.6 (the current release) if you can use that. https://github.com/pytorch/pytorch/pull/40676/files .

Have you made the pytorch header changes which we recommend at https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md ?

**Comment by BrknKybrd** [comment]
I had not made these changes, as the file specifies that they should only be done "If you are using pre-compiled pytorch 1.4 and torchvision 0.5, you should make the following changes to the pytorch source code to successfully compile with Visual Studio 2019 (MSVC 19.16.27034) and CUDA 10.1.".

# pytorch 1.6 and cast.h changes
I have now installed the current version of pytorch and torchvision and made the following changes as requested in install.md
Change python/Lib/site-packages/torch/include/csrc/jit/script/module.h
Change python/Lib/site-packages/torch/include/csrc/jit/argument_spec.h
- These files do not exist for me. Specifically I do not have a csrc subfolder. I have one at E:\conda-env\Lib\site-packages\torch\include\torch\csrc\jit but even that one does not contain these headers.

Change python/Lib/site-packages/torch/include/pybind11/cast.h
- This file I changed

With these changes the error message is 
[full2.txt](https://github.com/facebookresearch/pytorch3d/files/5089578/full2.txt)

# Hacky modifications to argument_spec.h 
I have an argument_spec.h file under E:\conda-env\Lib\site-packages\torch\include\torch\csrc\jit\runtime
where on Line 160 i can do
```
-static constexpr size_t DEPTH_LIMIT = 128;
+static const size_t DEPTH_LIMIT = 128;
```
[full3.txt](https://github.com/facebookresearch/pytorch3d/files/5089638/full3.txt)


# Hacky modifications to module.h
For module.h I cannot find a fine that would include the required text
`static constexpr *`
However, the error messages 
```
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(483): error: a member with an in-class initializer must be const
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(496): error: a member with an in-class initializer must be const
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(510): error: a member with an in-class initializer must be const
E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(523): error: a member with an in-class initializer must be const
```
above seem to imply that the corresponding file would be: 
E:\conda-env\Lib\site-packages\torch\include\torch\csrc\jit\api)

which contains commands such as:
`static CONSTEXPR_EXCEPT_WIN_CUDA bool all_slots = false;};`

When I change these lines to
`static const bool all_slots = false;`

the installation goes through:
[full4.txt](https://github.com/facebookresearch/pytorch3d/files/5089682/full4.txt)

## testcases
For further information I have ran the unittests, which returns 9 errors and 11 skips, mostly related to
`RuntimeError: CUDA error: invalid device ordinal`
[unittests.txt](https://github.com/facebookresearch/pytorch3d/files/5089721/unittests.txt)

**Comment by bottler** [comment]
As you can see, pytorch hasn't always kept its header files MSVC-compatible in the past. Well done for getting there and thank you for posting your experiences.

**Comment by BrknKybrd** [comment]
Please feel free to use this information to update the installation instructions. I could update it myself if you want, but maybe it is better if somebody that actually understands the context does it.

**Comment by Chokerino** [comment]
Im facing the same issue. Is there any fix while using pytorch==1.5.1

**Comment by bottler** [comment]
@Chokerino I think you can use the fixes described in Install.md as amended in PR #203. See https://github.com/facebookresearch/pytorch3d/pull/203/files

**Comment by Chokerino** [comment]
@bottler isnt that for pytorch 1.4? Also the cuda specified is 10.1 while im on 10.2. Also, I cant find the files mentioned in the Install.md so I don't think its meant for me.

**Comment by bottler** [comment]
I am not an expert on this. The details in Install.md are targetting pytorch 1.4. But my understanding of that pull request is that it makes the changes to Install.md to make it relevant to pytorch 1.5. 

You may be able to find the relevant files by looking at the compiler output you are getting - save it to a file and search for the first occurrences of "error". They will be deep inside wherever pytorch is installed. I don't know if the version of cuda matters much to any of these issues.

**Comment by totomobile43** [comment]
I followed BrknKybrd's instructions and was able to get the examples running. (with torch 1.6, cuda 10.1).

**Comment by RAJA-PARIKSHAT** [comment]
> The full error message shows that you've got these errors, which have been reported elsewhere.
> 
> ```
> E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(474): error: member "torch::jit::detail::ModulePolicy::all_slots" may not be initialized
> E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(487): error: member "torch::jit::detail::ParameterPolicy::all_slots" may not be initialized
> E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(501): error: member "torch::jit::detail::BufferPolicy::all_slots" may not be initialized
> E:/conda-env/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(514): error: member "torch::jit::detail::AttributePolicy::all_slots" may not be initialized
> ```
> 
> It looks like this might work in pytorch 1.6 (the current release) if you can use that. https://github.com/pytorch/pytorch/pull/40676/files .
> 
> Have you made the pytorch header changes which we recommend at https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md ?

What do you mean by header changes can you explain please.

**Comment by bottler** [comment]
@RAJA-PARIKSHAT Let's discuss on the other issue / another issue. This issue is resolved and old.
