### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by DaddyJin** [facebookresearch/pytorch3d#309]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
<put diff or code here>
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
<put logs here>
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by ashwath98** [comment]
I had the same issue, I installed the library from source and it was resolved(cpu). It can also be fixed if you use the nightly build (gpu)

**Comment by yuyingyeh** [comment]
I had the same issue +1. I installed the library from `conda install pytorch3d -c pytorch3d`

**Comment by jin0kim** [comment]
I also had this issue. I installed from pypi (pytorch3d-0.2.0)

**Comment by yuyingyeh** [comment]
> I had the same issue, I installed the library from source and it was resolved(cpu). It can also be fixed if you use the nightly build (gpu)

I tried `conda install pytorch3d -c pytorch3d-nightly` but there is another error when we import Textures from pytorch3d.structures:

```
from pytorch3d.structures import Meshes, Textures
ImportError: cannot import name 'Textures' from 'pytorch3d.structures' (/opt/conda/envs/pytorch-py37/lib/python3.7/site-packages/pytorch3d/structures/__init__.py)
```

**Comment by ashwath98** [comment]
textures is in renderer now, so you can from pytorch3d.renderer import  Textures

**Comment by AsaphLightricks** [comment]
I also have this issue. I'm working on mac os 10.14. At first i installed through pip, then directly from the source, in both cases i get the same error. Any solution?

**Comment by ashwath98** [comment]
I don't know if it will work for you but these were the steps I followed on popOS 20.04 in a new virtual environment

pip install pytorch3d
pip uninstall pytorch3d
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d
pip install -e .

**Comment by AsaphLightricks** [comment]
@ashwath98 thanks! it now works (with the removal of 'Textures' from the import)

**Comment by nashapir** [comment]
Hey, I'm working in macOS 12.1 and running into a similar error...

`Traceback (most recent call last):
    pyrender_camera = FoVOrthographicCameras(device=device, R=R_, T=T_)
  File ".../pytorch3d/pytorch3d/renderer/cameras.py", line 798, in __init__
    super().__init__(
  File ".../pytorch3d/pytorch3d/renderer/utils.py", line 112, in __init__
    self.device = make_device(device)
  File "...pytorch3d/pytorch3d/common/types.py", line 28, in make_device
    if device.type == "cuda" and device.index is None:  # pyre-ignore[16]
AttributeError: 'NoneType' object has no attribute 'type'`

I began with using pypi and then tried following ashwath98's instructions, installing from a clone. Would love any suggestions. Thanks!

**Comment by lhiceu** [comment]
> 

same issue. How did you solve it?
