### ISSUE TITLE
Update minimum requiered python version

### ISSUE THREAD

**Issue by shpotes** [facebookresearch/pytorch3d#77]
## [doc] 🐛 Bugs

As dataclasses were included in Python 3.7 some modules are broken in Python 3.6, but the installation guide suggests Python 3.6 as default version (see [this](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md#L20))

The following error arises when running one of the examples using a conda installation in Python 3.6
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ff7862b75591> in <module>
     18 
     19 # rendering components
---> 20 from pytorch3d.renderer import (
     21     OpenGLPerspectiveCameras, look_at_view_transform, look_at_rotation,
     22     RasterizationSettings, MeshRenderer, MeshRasterizer, BlendParams,

~/anaconda3/envs/torch3d/lib/python3.6/site-packages/pytorch3d/renderer/__init__.py in <module>
     17 from .lighting import DirectionalLights, PointLights, diffuse, specular
     18 from .materials import Materials
---> 19 from .mesh import (
     20     GouradShader,
     21     MeshRasterizer,

~/anaconda3/envs/torch3d/lib/python3.6/site-packages/pytorch3d/renderer/mesh/__init__.py in <module>
      2 
      3 from .rasterize_meshes import rasterize_meshes
----> 4 from .rasterizer import MeshRasterizer, RasterizationSettings
      5 from .renderer import MeshRenderer
      6 from .shader import (

~/anaconda3/envs/torch3d/lib/python3.6/site-packages/pytorch3d/renderer/mesh/rasterizer.py in <module>
      3 
      4 
----> 5 from dataclasses import dataclass
      6 from typing import NamedTuple, Optional
      7 import torch

ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by bottler** [comment]
We have removed dataclasses from master, so that pytorch3d will work on python3.6 if you install straight from github. We hope to have a new version uploaded to conda soon as well.

**Comment by bottler** [comment]
See also #72

**Comment by merlinND** [comment]
@bottler Just a head's up, I think another similar issue snuck into the current release (0.2.5):

```
..../.local/lib/python3.6/site-packages/pytorch3d/io/obj_io.py in load_obj(f, load_textures, create_texture_atlas, texture_atlas_size, texture_wrap, device)
    206         #  bytes]]]` for 1st param but got `Union[_PathLike[typing.Any], bytes, str]`.
    207         data_dir = os.path.dirname(f)
--> 208     with _open_file(f, "r") as f:
    209         return _load_obj(
    210             f,

..../.local/lib/python3.6/site-packages/pytorch3d/io/utils.py in _open_file(f, mode)
     20         return contextlib.closing(f)
     21     else:
---> 22         return contextlib.nullcontext(f)
     23 
     24 

AttributeError: module 'contextlib' has no attribute 'nullcontext'
```

`contextlib.nullcontext` was introduced in Python 3.7.

**Comment by bottler** [comment]
@merlinND Thanks for pointing this out. I think that commit fixes it.
