### ISSUE TITLE
How to install Pytorch3D in Windows 

### ISSUE THREAD

**Issue by sniperc96** [facebookresearch/pytorch3d#1159]
Hi
I am trying to install Pytorch3D in Windows10 with CUDA 10.1, cuDNN 7.6.5, and Pytorch 1.4.0. I tried the following commands and got the following errors.
Would you mind letting me know what I did wrong and how to correctly install it?
Thank you very much for your time and help!

1. Install from local: python setup.py install
```
running install
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pytorch3d._C' extension

Traceback (most recent call last):
  File "setup.py", line 144, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\torch\utils\cpp_extension.py", line 373, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\torch\utils\cpp_extension.py", line 363, in win_wrap_compile
    extra_postargs, depends)
  File "D:\Acaconda\envs\MeInGame37\lib\distutils\_msvccompiler.py", line 396, in compile
    self.spawn(args)
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\torch\utils\cpp_extension.py", line 351, in spawn
    cflags = COMMON_MSVC_FLAGS + self.cflags['cxx']
KeyError: 'cxx'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\Acaconda\envs\MeInGame37\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
    return stream.closed
ValueError: underlying buffer has been detached
```

**Comment by bottler** [comment]
PyTorch 1.4.0 is quite old. What version of visual studio do you have? It is possible that you have a version of visual studio which is too new for that version of PyTorch to support. 

Did you modify the line `extra_compile_args = {"cxx": ["-std=c++14"]}` in setup.py? If you need to remove the c++14 flag, I think `extra_compile_args = {"cxx": []}` would be safest. (Some change to this could be linked to the `KeyError: 'cxx'` error.)

PyTorch3D currently supports only PyTorch 1.7.0 or newer. If this problem is fixed, I am not sure how much will work anyway.

**Comment by sniperc96** [comment]
Hello,my version of visual studio is 2019,is it too new for PyTorch 1.4.0?
And I modified the line extra_compile_args = {"cxx": ["-std=c++14"]} in setup.py,but it did not work
Here is the output.
[error.txt](https://github.com/facebookresearch/pytorch3d/files/8426293/error.txt)

**Comment by sniperc96** [comment]
By the way,I install PyTorch3d 0.4.0,not 0.6.0.

**Comment by sniperc96** [comment]
Hello, I have changed my Anaconda's virtual environment,now it is Windows10 with CUDA 11.1, cuDNN 8.2.1, and Pytorch 1.7.1.
And I tried to install PyTorch3d 0.6.0,it still has some problems.
```
D:\Acaconda\envs\pytorch3d\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\Acaconda\envs\pytorch3d\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\Acaconda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
D:\Acaconda\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc' failed: None
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\Acaconda\envs\pytorch3d\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
    return stream.closed
ValueError: underlying buffer has been detached

running install
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing entry points to pytorch3d.egg-info\entry_points.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
adding license file 'LICENSE'
adding license file 'LICENSE-3RD-PARTY'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pytorch3d._C' extension
creating build\temp.win-amd64-3.8\Release\install package\study\pytorch3d-0.6-main\pytorch3d\csrc\interp_face_attrs
creating build\temp.win-amd64-3.8\Release\install package\study\pytorch3d-0.6-main\pytorch3d\csrc\pulsar\cuda
creating build\temp.win-amd64-3.8\Release\install package\study\pytorch3d-0.6-main\pytorch3d\csrc\rasterize_coarse
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc" -c "D:\install package\study\pytorch3d-0.6-main\pytorch3d\csrc\ball_query\ball_query.cu" -o "build\temp.win-amd64-3.8\Release\install package\study\pytorch3d-0.6-main\pytorch3d\csrc\ball_query\ball_query.obj" "-ID:\install package\study\pytorch3d-0.6-main\pytorch3d\csrc" "-ID:\install package\study\cub-1.10.0" -ID:\Acaconda\envs\pytorch3d\lib\site-packages\torch\include -ID:\Acaconda\envs\pytorch3d\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Acaconda\envs\pytorch3d\lib\site-packages\torch\include\TH -ID:\Acaconda\envs\pytorch3d\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -ID:\Acaconda\envs\pytorch3d\include -ID:\Acaconda\envs\pytorch3d\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 --use-local-env

```

**Comment by bottler** [comment]
> Hello,my version of visual studio is 2019,is it too new for PyTorch 1.4.0? And I modified the line extra_compile_args = {"cxx": ["-std=c++14"]} in setup.py,but it did not work Here is the output. [error.txt](https://github.com/facebookresearch/pytorch3d/files/8426293/error.txt)

The error mentions "fatal error C1083" and "cuda_runtime_api.h", so I wonder if the CUDA_HOME environment variable is set correctly.

**Comment by bottler** [comment]
> And I tried to install PyTorch3d 0.6.0,it still has some problems.

Can I suggest using the current `main` branch instead? You will find other recent windows build issues with `ball_query`, like the failing line here, which I hope have been fixed by commit f2cf9d4.

**Comment by bottler** [comment]
No, CUDA_HOME. To build programs with CUDA, CUDA_HOME should be set to the directory of the installed nvidia cuda toolkit which you want to use.

I've spotted something else: You want to use CUDA 11.1, but this output refers to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc", which is a 10.1 CUDA toolkit. That might be the same problem. I think you might want to set CUDA_HOME to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" , if you have installed cuda 11.1 there.

**Comment by sniperc96** [comment]
> 不，CUDA_HOME。要使用 CUDA 构建程序，应将 CUDA_HOME 设置为您要使用的已安装 nvidia cuda 工具包的目录。
> 
> 我发现了其他东西：您想使用 CUDA 11.1，但此输出指的是“C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc”，这是一个 10.1 CUDA 工具包。那可能是同样的问题。如果您在那里安装了 cuda 11.1，我认为您可能希望将 CUDA_HOME 设置为 "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" 。

Hello,I set the CUDA_HOME as "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1",it still fails.

D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "D:\Acaconda\envs\deep3d\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 159, in <module>
    "": ["*.json"],
  File "D:\Acaconda\envs\deep3d\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Acaconda\envs\deep3d\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Acaconda\envs\deep3d\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Acaconda\envs\deep3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Acaconda\envs\deep3d\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\bdist_egg.py", line 169, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\bdist_egg.py", line 155, in call_command
    self.run_command(cmdname)
  File "D:\Acaconda\envs\deep3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Acaconda\envs\deep3d\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Acaconda\envs\deep3d\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Acaconda\envs\deep3d\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Acaconda\envs\deep3d\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "D:\Acaconda\envs\deep3d\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Acaconda\envs\deep3d\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\Acaconda\envs\deep3d\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Acaconda\envs\deep3d\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Acaconda\envs\deep3d\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\Acaconda\envs\deep3d\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
    return stream.closed
ValueError: underlying buffer has been detached

[error.txt](https://github.com/facebookresearch/pytorch3d/files/8449182/error.txt)

**Comment by sniperc96** [comment]
> No, CUDA_HOME. To build programs with CUDA, CUDA_HOME should be set to the directory of the installed nvidia cuda toolkit which you want to use.
> 
> I've spotted something else: You want to use CUDA 11.1, but this output refers to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc", which is a 10.1 CUDA toolkit. That might be the same problem. I think you might want to set CUDA_HOME to "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" , if you have installed cuda 11.1 there.

I tried to use "x64 Native Tools Command Prompt for VS 2019" to compile and install,it failed.
D:\Acaconda\envs\deep3d\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)

**Comment by bottler** [comment]
The latest error.txt is hard to understand and full of errors. When I see things like `in C++14 'constexpr' will not imply 'const'; consider explicitly specifying 'const'` it makes me think the compiler is very old - i.e. pre C++14. So somehow the wrong compiler is being picked up. 

I don't know how important the warnings about `Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte` are. They have something to do with code pages / internationalization. The suggestion at https://github.com/NVlabs/stylegan2-ada-pytorch/issues/48 is to set the encoding to utf-8 but I'm not sure where. Maybe for the terminal? Can you look in to this?

**Comment by WenM1222** [comment]
I also met the same error,  after set "`set PYTHONIOENCODING=UTF-8`" before the command "`pip install -e .`", this error disappeared, but I encountered different errors: ` File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 619, in win_wrap_ninja_compile
        from distutils.spawn import _nt_quote_args  # type: ignore
    ImportError: cannot import name '_nt_quote_args' from 'distutils.spawn'.`   I saw one article said my setuptools is too new, so i downgraded it: setuptools=61.2.0-> 59.6. After that, I got this error:  `File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension`.  
I am using windows 10, pytorch 1.7.0, cuda11.3,  visual studio 2019

**Comment by bottler** [comment]
@WenM1222 The `_run_ninja_build` problem should be a build problem with an associated log file with more details - please look for that and open a new issue if you still need help.

**Comment by 3a1b2c3** [comment]
Did you get it to work in the end?
