### ISSUE TITLE
The version of PyTorch that matches PyTorch 3D 0.4.0

### ISSUE THREAD

**Issue by faneggs** [facebookresearch/pytorch3d#603]
What version of PyTorch matches the latest version PyTorch 3D 0.4.0？

**Comment by nikhilaravi** [comment]
@faneggs we support several versions of PyTorch - please have a look at [`INSTALL.md`](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) for more details.

**Comment by faneggs** [comment]
> @faneggs we support several versions of PyTorch - please have a look at [`INSTALL.md`](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) for more details.

After I installed Pytorch1.4.0 and Python3.6, I run `conda install pytorch3d -c pytorch3d`, PyTorch3D 0.2.0 is installed by default. But I wanna install PyTorch3D 0.4.0. My configuration is Ubuntu18.04 and cudatoolkit 10.0.

**Comment by bottler** [comment]
We borrow a docker image from PyTorch's build infrastructure to do builds for PyTorch3D. A few months ago PyTorch itself stopped doing builds with CUDA 10.0, and the image no longer had CUDA 10.0 available. We therefore stopped building PyTorch3D with CUDA 10.0. PyTorch 0.2.0 was the last version before the change.

Is there a reason you need to stay with CUDA 10.0?

Note that PyTorch3D still makes builds for non-current versions of PyTorch, but only using versions of CUDA which PyTorch still supports. CUDA 9.2 is still supported.

**Comment by xhuan8** [comment]
we have to use CUDA 10.0 for some history modules, is it possible to add it back for 0.4.0?

**Comment by bottler** [comment]
@xhuan8 can you build PyTorch3D from source?

**Comment by xhuan8** [comment]
@bottler got many build errors
pytorch version 1.4.0

/home/xiehuan/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::CrossMapLRN2dImpl]’:
    /tmp/tmpxft_00005394_00000000-5_sigmoid_alpha_blend.cudafe1.stub.c:32:27:   required from here
    /home/xiehuan/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch::OrderedDict<std::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::basic_string<char>, at::Tensor>&’
    /home/xiehuan/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch::OrderedDict<std::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::basic_string<char>, at::Tensor>&’
    /home/xiehuan/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch::OrderedDict<std::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::basic_string<char>, std::shared_ptr<torch::nn::Module> >&’
    /home/xiehuan/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::EmbeddingBagImpl]’:

**Comment by bottler** [comment]
This is the same problem as #284. Which version of PyTorch are you using, and what compiler are you using?

**Comment by xhuan8** [comment]
@bottler you are right, it's the same problem as #284 
I'm using PyTorch 1.4 and gcc 5.4
Unfortunately i cannot upgrade PyTorch nor CUDA

**Comment by bottler** [comment]
I think this might work if you use a newer version of GCC. (You can try doing the build on a separate machine / container if you can't change locally.)
 If you can't do that, maybe you can replicate the changes in https://github.com/pytorch/pytorch/pull/37221 in your local PyTorch headers.

**Comment by xhuan8** [comment]
fixed with changes in PyTorch, thanks a lot
