### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Chenhait** [facebookresearch/pytorch3d#923]
hi,i meet a problem when import pytorch3d
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from loss import SILogLoss, BinsChamferLoss
  File "/home/oem/下载/adb/AdaBins-main/loss.py", line 3, in <module>
    from pytorch3d.loss import chamfer_distance
  File "/home/oem/anaconda3/envs/adb3/lib/python3.8/site-packages/pytorch3d/loss/__init__.py", line 4, in <module>
    from .chamfer import chamfer_distance
  File "/home/oem/anaconda3/envs/adb3/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 7, in <module>
    from pytorch3d.ops.knn import knn_gather, knn_points
  File "/home/oem/anaconda3/envs/adb3/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/oem/anaconda3/envs/adb3/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

**Comment by bottler** [comment]
Please explain your setup, print `conda list` and `conda info`, and explain how you built PyTorch3D.

Does `import torch` work? What does `torch.cuda.is_enabled()` return?

**Comment by Chenhait** [comment]
> Please explain your setup, print `conda list` and `conda info`, and explain how you built PyTorch3D.
> 
> Does `import torch` work? What does `torch.cuda.is_enabled()` return?

thank you for replying!here are some information.

[chenhaitao@dgx01 AdaBins-main]$ conda list
# packages in environment at /nfs/home/chenhaitao/.conda/envs/pytorch1.6-cuda10.20.0.:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
anyio                     3.3.0            py38h578d9bd_0    conda-forge
argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.3                    pypi_0    pypi
configparser              5.1.0                    pypi_0    pypi
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.4.1            py38h709712a_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docker-pycreds            0.4.0                    pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20211023          pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.24                   pypi_0    pypi
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.8.1            py38h578d9bd_0    conda-forge
intel-openmp              2021.3.0          h06a4308_3350  
iopath                    0.1.9                    pypi_0    pypi
ipykernel                 6.4.1            py38he5a9106_0    conda-forge
ipython                   7.27.0           py38he5a9106_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h7f8727e_0  
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            7.0.3              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py38h578d9bd_0    conda-forge
jupyter_server            1.11.0             pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.12             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.1              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libwebp-base              1.2.0                h27cfd23_0  
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h497a2fe_1004    conda-forge
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.2            py38h51133e4_0  
nbclassic                 0.3.2              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py38h578d9bd_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
ninja                     1.10.2               hff7bd54_1  
notebook                  6.4.4              pyha770c72_0    conda-forge
numpy                     1.20.3           py38hf144106_0  
numpy-base                1.20.3           py38h74d4b33_0  
olefile                   0.46               pyhd3eb1b0_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandoc                    2.14.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.1            py38h2c7a002_0  
pip                       21.0.1           py38h06a4308_0  
portalocker               2.3.2                    pypi_0    pypi
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.11          h12debd9_0_cpython  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorch3d                 0.3.0                    pypi_0    pypi
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     19.0.2           py38ha71036d_2    conda-forge
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-unixsocket       0.2.0                      py_0    conda-forge
scipy                     1.7.2                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
sentry-sdk                1.4.3                    pypi_0    pypi
setuptools                58.0.4           py38h06a4308_0  
shortuuid                 1.0.7                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0  
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.2.0            py38h578d9bd_1    conda-forge
sqlite                    3.36.0               hc218d9a_0  
subprocess32              3.5.4                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.12.1           py38h578d9bd_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               hbc83047_0  
torchvision               0.7.0                py38_cu102    pytorch
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
typing-extensions         3.10.0.2                 pypi_0    pypi
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wandb                     0.12.6                   pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          0.57.0           py38h578d9bd_4    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
yaspin                    2.1.0                    pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  
[chenhaitao@dgx01 AdaBins-main]$ conda info

     active environment : pytorch1.6-cuda10.20.0.
    active env location : /nfs/home/chenhaitao/.conda/envs/pytorch1.6-cuda10.20.0.
            shell level : 1
       user config file : /nfs/home/chenhaitao/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.4=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /nfs/opt/cascadelake/linux-centos7-haswell/gcc-4.8.5/miniconda3-4.9.2-sf52aswrczlmgw5qqe4mnhcohf4waknb  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfs/opt/cascadelake/linux-centos7-haswell/gcc-4.8.5/miniconda3-4.9.2-sf52aswrczlmgw5qqe4mnhcohf4waknb/pkgs
                          /nfs/home/chenhaitao/.conda/pkgs
       envs directories : /nfs/home/chenhaitao/.conda/envs
                          /nfs/opt/cascadelake/linux-centos7-haswell/gcc-4.8.5/miniconda3-4.9.2-sf52aswrczlmgw5qqe4mnhcohf4waknb/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/3.10.0-1160.42.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1028:1028
             netrc file : None
           offline mode : False

[chenhaitao@dgx01 AdaBins-main]$ python
Python 3.8.11 (default, Aug  3 2021, 15:09:35) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_enabled()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.cuda' has no attribute 'is_enabled'
>>> torch.cuda.is_available()
True

**Comment by bottler** [comment]
How did you install PyTorch3D? It is necessary to follow the instructions in INSTALL.md. 

We used to maintain linux packages on PyPI, and it looks like you might have one from there. The Linux PyPI packages from PyTorch3D 0.3.0 used CUDA 10.1, they won't work in your environment with CUDA 10.2.

**Comment by Chenhait** [comment]
> Please explain your setup, print `conda list` and `conda info`, and explain how you built PyTorch3D.
> 
> Does `import torch` work? What does `torch.cuda.is_enabled()` return?

thank you so much for your reply. I try to install pytorch3d using the way in install.md.

however, there is a error when I try 'pip install -e .'


<img width="924" alt="截屏2021-11-11 下午3 13 16" src="https://user-images.githubusercontent.com/68895932/141254762-9cf9b5a2-9bca-402c-8b78-5a82b25cd9fa.png">

**Comment by Chenhait** [comment]
> > Please explain your setup, print `conda list` and `conda info`, and explain how you built PyTorch3D.
> > Does `import torch` work? What does `torch.cuda.is_enabled()` return?
> 
> thank you so much for your reply. I try to install pytorch3d using the way in install.md.
> 
> however, there is a error when I try 'pip install -e .'
> 
> <img alt="截屏2021-11-11 下午3 13 16" width="924" src="https://user-images.githubusercontent.com/68895932/141254762-9cf9b5a2-9bca-402c-8b78-5a82b25cd9fa.png">

here are my inputs

conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=10.2
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
conda install pytorch3d -c pytorch3d
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d
pip install -e .

**Comment by bottler** [comment]
Is there a log file from the build? Or is there an actual compiler error above the stacktrace you have pasted?

**Comment by nikhilaravi** [comment]
@Chenhait do you still need help with this issue?

**Comment by Chenhait** [comment]
> @Chenhait do you still need help with this issue?



> @Chenhait do you still need help with this issue?

thank you very much. I installed with the guide, and problem is solved.
