### ISSUE TITLE
Fail to build after #69041

### ISSUE THREAD

**Issue by tobyclh** [facebookresearch/pytorch3d#995]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

Building pytorch3d from github master shows the following error
```
  /tmp/pip-req-build-efpu1n0n/pytorch3d/csrc/pulsar/pytorch/renderer.cpp:944:3: error: ‘TORCH_CHECK_ARG’ was not declared in this scope
     TORCH_CHECK_ARG(
     ^~~~~~~~~~~~~~~
  /tmp/pip-req-build-efpu1n0n/pytorch3d/csrc/pulsar/pytorch/renderer.cpp:944:3: note: suggested alternative: ‘TORCH_CHECK_MSG’
     TORCH_CHECK_ARG(
     ^~~~~~~~~~~~~~~
     TORCH_CHECK_MSG
```
## Instructions To Reproduce the Issue:
`pip install "git+https://github.com/facebookresearch/pytorch3d.git"`

This seems to be introduced by a very recent commit in
https://github.com/facebookresearch/pytorch3d/blob/f8fe9a2be144cf3c7c047e05d59605474f3a8bdb/pytorch3d/csrc/pulsar/host/commands.h#L158

**Comment by tobyclh** [comment]
I can successfully compile using the previous commit d049cd2e0102a6b2e08bf2b595131d5177638081.

**Comment by bottler** [comment]
Let me fill in what has happened. This is a failure to build PyTorch3D from source at the latest commit on main, which is https://github.com/facebookresearch/pytorch3d/commit/f8fe9a2be144cf3c7c047e05d59605474f3a8bdb . That commit was roughly synchronised with a PR https://github.com/pytorch/pytorch/pull/69041 in PyTorch itself. Bleeding-edge PyTorch and PyTorch3D get tested together and are fine together but the change in PyTorch3D won't work with released versions of PyTorch which PyTorch3D aims to support. I hope to make a further change to PyTorch3D to restore compatibility.

**Comment by tobyclh** [comment]
I appreciate the quick response!
Thank you!
